### PR TITLE
Addition of DASH and HLS demo content from MetaCDN

### PR DESCRIPTION
**Pull request by CaitlinOCallaghan**
## Description

Addition of StreamShark (MetaCDN) HLS and DASH sample content for 180 degree and HD video.

## Checklist:

- [x] I have signed the Google CLA <https://cla.developers.google.com>
- [x] My code follows the style guidelines of this project
- [x] I have verified my change on multiple browsers on different platforms
- [x] I have run `./build/all.py` and the build passes
- [x] I have run `./build/test.py` and all tests pass

### CODE REVIEW

**Comment by CaitlinOCallaghan** [comment]
@googlebot I signed it!

**Comment by CaitlinOCallaghan** [comment]
@googlebot I signed it!

**Review by joeyparrish — APPROVED** [review]

**Comment by CaitlinOCallaghan** [comment]
@googlebot I signed it!

**Comment by TheModMaker** [comment]
Your CLA is still invalid.  Make sure the email you use to sign it exactly matches the email in your commits.  Since you're using a company email,  if you use a corporate CLA, you need to be on the allowed list of emails (and again, it must match exactly).  I also don't see a corporate CLA for "streamshark", so it may not be valid yet.

**Comment by CaitlinOCallaghan** [comment]
Thanks! Our CEO just signed the CLA form yesterday; another employee was the one who initially filled it out. I believe the CLA will be under either MetaCDN or StreamShark, as our company has two names.

**Comment by CaitlinOCallaghan** [comment]
@googlebot I signed it!

**Review by michellezhuogg — APPROVED** [review]

**Comment by joeyparrish** [comment]
Thanks!

**Comment by kevleyski** [comment]
Thanks again Joey and Caitlin!

**Pull request merged**
