### PR TITLE
add manifest.dash.ignoreEmptyAdaptationSet config option

### PR DESCRIPTION
**Pull request by leonchen**
for #2023

### CODE REVIEW

**Comment by leonchen** [comment]
@googlebot I signed it!

**Comment by avelad** [comment]
I think that the PR doesn’t include demo locales.

**Comment by joeyparrish** [comment]
Oops!  You're right.  There's no definition for `DEMO_IGNORE_DASH_EMPTY_ADAPTATION_SET`.  We should add that, and come up with a test to catch those mistakes before they are merged.

**Comment by joeyparrish** [comment]
I just landed a change to add the missing message.  I have a test in review which would catch these mistakes in future.

**Comment by joeyparrish** [comment]
Just landed the new test as well.  Thanks to @leonchen for the PR, and to @avelad for pointing out the missing message.

**Comment by joeyparrish** [comment]
This PR has been cherry-picked for v2.5.8.

**Pull request merged**
