### PR TITLE
Fix seekbar behavior when arrow key is pressed for long #3234

### PR DESCRIPTION
**Pull request by surajkumar-sk**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

the issue mentioned in #3234 is fixed.

https://user-images.githubusercontent.com/71056993/111549665-d157a600-8739-11eb-933d-1f6719edfab3.mp4

.
Fixes # (issue)
#3234 
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by surajkumar-sk** [comment]
No code has been replaced and no variables already present are reassigned, so there will not be any conflicts with other controls. 
when a user playing the video keeps the arrow key pressed for long, the user intends to use forward or backward video browsing continuously. As the event manager listens to key down for the window an if-condition is added `!this.controlsContainer_.classList.contains('shaka-keyboard-navigation)'` so if the video-container is not in focus the seek bar updating statements won't run as `controlContainer_` has class `'shaka-keyboard-navigation'` only when videoContainer_ is on focus or Keyboard Controls are enabled by the at the app level. 

The seek bar should start continuously moving forward or backward only when the user keeps the arrow key pressed for at least a second. That can be accomplished by saving the time when the Eventmanger listens to key-down and executes `onKeyDown_()`  and adding an if condition checking whether the key-up is triggered after 1s of key-down event. the variable `this.continuousSeekBarUpdatingTimer_` checks if the time when the key-down event is triggered is assigned to the variable `this.continuousSeekBarUpdatingTime_` or not . so if it is true it won't keep assigning the time to the variable. this time variable is used in further if-condition to check if the present time is more than 1sec from the time assigned in variable and if true starts updating the seek-bar.

for updating seek bar two timers are assigned `this.seekbarIncreaseTimer_` `this.seekbarDecreaseTimer_` which extends class `Shaka.util.Timer` these timers tick every 0.1s and update the seek bar by 2s forward or backward. These timers are stopped when the Event manager triggers key-up and executes `onKeyUp_()`. 

Now when the seek bar gets updated in function `onKeyDown_()` its shouldn't be updating in `onKeyUp_()` so the variable `this.continuousSeekBarUpdating_` becomes true if the seek bar is updated in `onKeyDown_()` and an if condition is used in  `onKeyUp_()` with `this.continuousSeekBarUpdating_` variable to check if seek bar is updated and to reassign the default values for `this.continuousSeekBarUpdating_` `this.continuousSeekBarUpdatingTimer_` and stopping the execution of `onKeyDown()` .

and also the timers should stop if the current time is less than 0 or when the video has ended. so an if condition is added for both. I think rather than having `this.video_.ended` it would be better to have a  condition like `this.video_.currentTime > this.video_.max ` something like this.

**Comment by joeyparrish** [comment]
Your solution looks a little too complicated to me.  I also don't like that you added left & right arrow key listeners on the window instead of the controls.

From what I can tell, there are two issues with the seek_() call in the key handler:

```js
this.seek_(this.video_.currentTime + 5, event);
```

Which then calls:

```js
this.video_.currentTime = currentTime;
```

First, updates to `video.currentTime` are not instantaneous.  They trigger a seek operation, and reading the value back out shows the current playback position.  So calling `seek_()` rapidly with `video.currentTime + 5` is not going to work consistently.  Though you won't see this on desktop Chrome, some platforms seek very slowly.

If you try clicking and dragging the seek bar, you'll find that we already have a system to handle rapid movements of the seek bar.  The seek is deferred until either the bar is released or the user stops moving the mouse for a moment.  While the user is moving the seek bar, the time read from the seek bar represents where the user's cursor is, not where the playback is.

I think I would prefer to fix this in a way that reuses that existing seek bar logic.

Second, we're calling `seek_()` from `keyup` events, which means when you're holding down the arrow, we're only getting one event when you let go.  So the rapid seeks you're seeing are from the input element's native key handling.  To support this holding down of the left & right arrows, we should be listening to `keydown` events instead (on the controls, though, not on window as in your change).

**Comment by joeyparrish** [comment]
I have an alternate fix in internal code review, so I'm going to close this PR.  I'll link to the commit here once the fix is merged.  Thanks for your contributions!

**Comment by surajkumar-sk** [comment]
@joeyparrish I taught it was better to add code in the existing function rather than creating a new event and adding a separate function. I did listen to key events on windows but added an if condition which would run the code below only if the video container is in focus. After watching your solution my code does seem very complicated and I also kind of feared breaking the code if I change the names of functions 😅 because I haven't fully completed reading this project. I think there was a reason for listening to key-up events because `this.pressedKeys_.delete(event.key);` should only run when the key is released. this definitely should create some kind of bug. I'll check for any bugs if any, caused by that change.

**Pull request closed without merging**
