### PR TITLE
Stall detector cause DOM error on SmartTV(issue #2920)

### PR DESCRIPTION
**Pull request by Yuvalke**
Avoid pause request when play request still in process.

### CODE REVIEW

**Comment by TheModMaker** [comment]
The whole point of the stall detector is to trigger when we are supposed to be playing but are not.  There are cases where the `readyState`, `playbackRate`, and `paused` all say we should be playing but the playhead doesn't move.  So we need to poke the media pipeline to fix it and get the browser to actually play.  This basically just disables the stall detector.

You can disable the stall detector with setting the `streaming.stallEnabled` config to `false`.  I'll also update the original bug and we can discuss a better fix.

**Comment by TheModMaker** [comment]
Actually, I got the condition backwards.  I still think this isn't the correct fix since this shouldn't be called for some of the conditions anyway and the error you list shouldn't cause any problems.  That function shouldn't be called when `paused` is true; we want to be called when `readyState` is any value since some browsers don't change it; and we can still get a stall at time 0.

**Comment by Yuvalke** [comment]
Hi @TheModMaker,
I wrote an update on the issue itself, this issue could happen AFAIK only on the first play request, maybe the correct solution is to enable the stall detector after `playing` or any other idea you have to know when playback play request didn't reject by the browser.
The native implementation after play promise rejected change `paused` to `false` so we have to call `pause` after promise rejected, so this rejection could cause issues.

**Comment by Yuvalke** [comment]
Hi @TheModMaker,
I thought about something else, expose the default config before it changed by device type, does it acceptable?

**Pull request closed without merging**
