### PR TITLE
Add missing goog.require for shaka.util.StringUtils

### PR DESCRIPTION
**Pull request by hochhaus**

### CODE REVIEW

**Comment by joeyparrish** [comment]
Good catch!  Please read CONTRIBUTING.md and follow the instructions.  You'll need to add yourself to CONTRIBUTORS and AUTHORS.

**Comment by hochhaus** [comment]
@joeyparrish Thanks. I updated the CONTRIBUTORS and AUTHORS files. Please let me know if I missed anything else.

PTAL

**Comment by joeyparrish** [comment]
Looks good to me.  Thanks!

**Comment by joeyparrish** [comment]
Thanks!

**Pull request merged**
