### PR TITLE
fix: memory leak after bundling 3.0.x branch and latest version with Webpack

### PR DESCRIPTION
**Pull request by Yuvalke**
tested with Webpack mode=production which caused the issue. 
Solve #3092

### CODE REVIEW

**Comment by Yuvalke** [comment]
Hi @joeyparrish can you please take a look? it fixes the issue on v3.0.x, if the next release will be from the master it'll be as part of it and solve the issue anyway.
Thanks

**Comment by joeyparrish** [comment]
This isn't merely working around your webpack issue.  It also changes the logic, and I'm not convinced that the change in logic is correct or worthwhile.

**Comment by Yuvalke** [comment]
I tested it, it fixes the issue with Treser(Webpack) not sure why yet, also the change here is part of your master branch so why doesn't it correct?

**Comment by joeyparrish** [comment]
Sorry, I didn't realize that was the newer code from `master`.  Let me dig into the history of that change and determine if it's appropriate to cherry-pick to v3.0.x.

**Comment by joeyparrish** [comment]
Okay, this change was made originally to support Low-Latency HLS's partial segments.  In that case, newer versions of a segment reference should always replace older ones.  When a playlist updates, and a given segment is no longer represented as partial segments, we should not try to fetch the partial segments from the old segment reference.

Understanding why that change was made, I see no reason we couldn't use it in v3.0.x.  This change not cherry-picked at the time because the LL-HLS features themselves are not cherry-pickable to v3.0.x (because they are new features and require a minor number release).

**Review by joeyparrish — APPROVED** [review]

**Comment by joeyparrish** [comment]
@Yuvalke, this is an issue that we fixed earlier.  Can you please rebase or merge recent changes from master?  Thanks!

**Comment by Yuvalke** [comment]
Hi @joeyparrish WDYM from master? I'm working specifically on v3.0.x, I guess we need to cherry-pick https://github.com/google/shaka-player/issues/3102 to v3.0.x to make it work, am I right?

**Comment by Yuvalke** [comment]
@joeyparrish BTW what is your next version? 3.0.8? 3.1.0?

**Comment by joeyparrish** [comment]
Sorry, we normally work from the `master` branch, so I didn't notice the PR was targeting `v3.0.x`.  Makes perfect sense, though.

I just updated `v3.0.x` with the fix as well.  Can you please rebase on `v3.0.x` to fix the build failure?  This can go into v3.0.8 if it lands today or tomorrow.  (I'll try to be flexible given how many timezones we cover in this community.)

**Comment by joeyparrish** [comment]
Actually, since I'm doing cherry-picks and a test pass right now anyway, I'll cherry-pick this change and include it in my test pass and push to v3.0.x.  This way, we are sure to be able to merge it today and move forward with the release as soon as possible.

**Comment by joeyparrish** [comment]
Tests passed when I cherry-picked this onto the top of v3.0.x.  I'll go ahead with the merge.

**Comment by Yuvalke** [comment]
@joeyparrish Thanks!

**Comment by joeyparrish** [comment]
@Yuvalke, we're always happy to help!

**Comment by OrenMe** [comment]
Hi @joeyparrish thanks for adding this. We are looking forward for the fix, have you already set a possible release date for 3.0.8?

**Pull request merged**
