### PR TITLE
Always build the same input files to a stable output

### PR DESCRIPTION
**Pull request by johan**
#299, but for the `preview` branch. As I haven't tested this and don't generally speak a lot of python, vet with extra caution.

### CODE REVIEW

**Comment by joeyparrish** [comment]
Let me investigate.  Our build bot is still fairly new, so this might be the bot's fault.

**Comment by johan** [comment]
Seems it builds happily at my end both before and after the change, so that sounds likely.

**Comment by joeyparrish** [comment]
There was a bug in the bot's job script.  We made a mistake in the v1-v2 transition.  Should be working for both branches now.

**Comment by joeyparrish** [comment]
@johan Thanks so much!

**Pull request merged**
