### PR TITLE
fix(HLS): skip whitespace in attributes

### PR DESCRIPTION
**Pull request by wjywbs**
## Description

Example manifest:
`#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=1000000, RESOLUTION=1920x1080`

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have signed the Google CLA <https://cla.developers.google.com>
- [x] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have verified my change on multiple browsers on different platforms
- [x] I have run `./build/all.py` and the build passes
- [x] I have run `./build/test.py` and all tests pass

### CODE REVIEW

**Comment by avelad** [comment]
@joeyparrish can you review it? Thanks!

**Comment by avelad** [comment]
@joeyparrish can you review it? Thanks!

**Review by joeyparrish — APPROVED** [review]
Thank you for this, and for adding a test!

**Comment by joeyparrish** [comment]
Looks like we merged another change that conflicts with this one.  Can you please take a look and add `sequenceMode: true` to your expected HLS manifest?

```
      ✗ parses manifest attributes with space
	Error: Expected $.sequenceMode = true to equal false.
```

**Comment by joeyparrish** [comment]
Oh, you'll need to rebase/merge, I expect

**Comment by joeyparrish** [comment]
I commited a quick fix to your PR branch to add the missing sequenceMode attribute.  I'm not sure if that's enough, or if the branch will have to be rebased, as well.  If the tests pass, I'll merge it.  Thanks!

**Review by joeyparrish — APPROVED** [review]

**Pull request merged**
