### PR TITLE
Accessibility Feature: Configurable Keyboard shortcut: toggleFullscreenOnfPress

### PR DESCRIPTION
**Pull request by Ketan2010**
## Description
for better accessibility keyboard shortcuts need to be added. This PR gives implementation of keyboard shortcut (f) which toggles fullscreen view of video. Which can be configured as existing UIConfigurations as follow.
```
const config = {
    toggleFullscreenOnfPress: true,
 };
```
Such more shortcuts can be implemented for other frequent controls like Picture in Picture, Mute and Unmute, Captions etc. 

Fixes # (issue)
#3223

## Screenshots (optional)

https://user-images.githubusercontent.com/57591621/111948015-7b517c80-8b04-11eb-9559-5a6f9a650682.mp4

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by surajkumar-sk** [comment]
@Ketan2010 Did you notice the number of lines added inside your commit . Its +58,168 .
I checked you commit and realised they are the lines from previous versions of shaka that were deleted or edited. If your pull request is accepted all the updates of shaka player will be removed so your pull request will be declined.  You will have to first merge the changes from this repo to your repo and  then add your code for full screen functionality and then send a pull request .

**Comment by surajkumar-sk** [comment]
@Ketan2010 
First thing first why is there +58,168 lines of code changes , could you please explain that ?
Second , you are listening to key up on windows which was clearly forbidden by members .
Third , there is a `oncontrolkeydown()` function in which you can write your switch case , why bother to create another function .

**Comment by surajkumar-sk** [comment]
@Ketan2010  you committed dist folder too, dist is a folder created when you run python build/all.py which is only for the local computer which has shaka-player compiled files used for creating shaka-player-based applications, you shouldn't commit it.

**Comment by Ketan2010** [comment]
@surajkumar-sk, Thank you for commenting.

As per contribution guidelines, 
1. First I fork latest version of shaka-player repository (today itself)
2. I perform changes in it, build (thats why dist folder may be created) and tested in my localhost.
3. Everything was working perfectly without any error.
4. Then I pushed and merge changes in my repository. 
5. And then sent pull request.

The reason behind making new function to handle key board shortcut is, If we want to add more configurable keyword shortcuts like this, then that can fall into that newly created function just to avoid mess.

The reason behind listening on windows is if user needs to click on controls first to access keyboard shortcuts then why we are building keyboard shortcuts? he can do that by clicking only. hence I listen to windows and not to video container.(even youtube video keyboard shortcuts works without clicking on controls or video container)

I don't know how much I am correct here. I just started with and need to explore more.
Thanks!

**Comment by surajkumar-sk** [comment]
@Ketan2010 The instructions are right but you don't have to commit dist folder. just use `git branch branchname` to create a branch then `git checkout brachname` to select the branch `git add` to add files you changed then `git commit -m "some message"` which commits to the local repo and then `git push origin branchname` to push changes to your GitHub repo and then create a pull request from 'branchname' to shaka player master.

**Comment by surajkumar-sk** [comment]
@Ketan2010 youtube is a web application that plays videos so youtube can have whatever controls they want for their player. But shaka-player is used as a plugin to create such applications and many applications have been created using shaka. now, if you introduce shortcut keys and if these shortcut keys are used by applications created by shaka for some other task then that might create conflicts. like the end-user might be using f to make his website go fullscreen rather than video. Users using shaka user might not like the video being controlled by keys because not all websites are just meant for video browsing like youtube. I think the user might get a choice to choose whether to listen to key events from video or window. and the default should be kept listening to events on the video container.

**Comment by nbcl** [comment]
Hello @Ketan2010 and @surajkumar-sk!

In this situation I would advice to create a new pull request with your same changes but make sure that `package-lock.json` and `dist/` are not being uploaded.

The distribution folder should have been removed by default via `.gitignore`, but if I am not mistaken, it appears that maybe doing the commits via https://github.com/ is overriding it.

Using git should solve this issue, but if you prefer, [GitHub Desktop](https://desktop.github.com/) is also an alternative that in my opinion is a better way to transition coming from the web interface.

> I think the user should get a choice to choose whether to listen to key events from video or window. and the default should be kept listening to events on the video container.

Finally, as @surajkumar-sk said, this feature should be optional, so it would have to default to `false` [here](https://github.com/Ketan2010/shaka-player/blob/master/ui/ui.js#L211).

Let me know if this helps.

**Comment by michellezhuogg** [comment]
Hello @Ketan2010 ,

Thank you for your contribution! I think it makes sense to listen on windows. "Key shortcuts" - which you're working on, and "Keyboard navigations" (for accessibility reasons) are two separate features, and let's make sure those two all work with your code change.

**Comment by michellezhuogg** [comment]
Not directly relevant to this PR, but it would be great if we document how our "keyboard navigation" works for accessibility in our tutorial, similar to [Youtube](https://support.google.com/youtube/answer/7631406?hl=en&ref_topic=9257412) .

**Comment by surajkumar-sk** [comment]
@michellezhuogg I am confused , what is the difference in keyboard navigation and shortcuts , they are the same thing with different names. Controlling video components with keyboard. Then why does one gets to listen on window and the other on video container. They both could be on windows. Could you please clarify . If anyone in the future come back to check why shortcuts were on windows this could help.
Thank you .

**Comment by Ketan2010** [comment]
#3270 PR considering all suggested changes.
1. listening to keydown on windows 
2. default to `false`
3. Committed only required changes.

Thanks!

**Comment by CodeDotJS** [comment]
@surajkumar-sk keyboard shortcuts can either be implemented by keeping the "app" (or component of an app) in context or the `window`. For example - when you hit `CTRL + N` in chrome, it opens a new window, but suppose you go to [codesandbox](https://codesandbox.io) and change the `when` expression in keyboard preferences to `editorTextFocus`, the same shortcut would open an empty file, but it only happens when the `editor` has `focus`. So, the same shortcut can perform two different actions in the same tab.

Now, in order to "__navigate__", you can either *define* a shortcut or use the default ones. Navigation usually sets the focus from one place to another where you can do "specific" things. For example - you can navigate from `close button` to `full screen` and hit enter to perform the action, on the other hand, you can hit __`F`__ (which is a shortcut) to go fullscreen.

**Comment by surajkumar-sk** [comment]
@CodeDotJS i understand that pressing f to go full-screen is a shortcut to avoid navigation. My concern is arrow keys are used to navigate through video only when videocontainer is brought into focus by tab, but f can be used without bringing the videocontainer into focus, if keyboard functionality is being used without getting videocontainer into focus, then why not do the same with arrow controls, what difference does it make if you listen to f on window and keys on container. When shortcut keys are listening on windows then even arrow keys space key , home and end keys are also shortcuts right, then why are we not listening to them on window.

**Pull request closed without merging**
