### PR TITLE
Account for segmentStartTime in vtt segments to handle live

### LINKED ISSUE #480: Segmented VTT - absolute or relative timestamps?
WebVTT segments are not syncing properly with live streams because they are not accounting for the `segmentStartTime`. The first cue in each segment starts at `00:00:00.000` so the `segmentStartTime` needs to be used to offset each segment properly.

### PR DESCRIPTION
**Pull request by sanbornhnewyyz**
Closes #480

### CODE REVIEW

**Comment by sanbornhnewyyz** [comment]
This would fix #480 and not break VOD as far as I can see.

**Comment by baconz** [comment]
I do not think there is clarity on whether the cues should be relative or absolute for live playback. Can we put this behind a config parameter so we don't break backwards compatibility for those of us who have already hacked around this :)

See:

https://github.com/google/ExoPlayer/issues/1493
https://github.com/Dash-Industry-Forum/Test-Vectors/issues/44

**Comment by sanbornhnewyyz** [comment]
Okay, this what I was worried about. I was looking for information on how VTT segment timestamps were supposed to be reported but I couldn't find any. I guess this is why.

A config parameter would require us to know ahead of time whether the cues we were going to get back had relative or absolute timestamps which seems less than ideal. But if I understand you correctly you're saying there is no other indication from the manifest?

**Comment by sanbornhnewyyz** [comment]
I'm going to reject this for now because it seems evident that this solution is incomplete and requires some additional discussion first.

**Pull request closed without merging**
