### PR TITLE
issue/1985-fromCharCode-enhancement

### PR DESCRIPTION
**Pull request by dobrusev**
For stringUtil.fromCharCode when creating a new string from the given array of char codes break the array in smaller chunks to avoid stack errors on low end devices

### CODE REVIEW

**Comment by dobrusev** [comment]
#1985

**Comment by joeyparrish** [comment]
Thank you for this contribution.  We spent some time discussing this internally, and we've decided to go with a slightly different fix, which will detect and adapt the chunk size to the device capabilities.

**Comment by dobrusev** [comment]
Sounds good! How can I track that change - I would like to get updates when that will be added thanks!

**Comment by joeyparrish** [comment]
It went out to the master branch in 7bbca07, and I'll cherry-pick that to v2.5.x and release it in v2.5.3.  In the mean time, you can use the master branch or our [nightly build on appspot](https://nightly-dot-shaka-player-demo.appspot.com/), which will have the fix around 4am PDT.

**Pull request closed without merging**
