### PR TITLE
fix: Add encrypted box on EC-3

### PR DESCRIPTION
**Pull request by nick-michael**
## Description
The fake encryption solution implemented for Xbox seems to be failing for streams that have EC-3 tracks so I've added an encryption box for that as well

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have signed the Google CLA <https://cla.developers.google.com>
- [x] My code follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have verified my change on multiple browsers on different platforms
- [x] I have run `./build/all.py` and the build passes
- [x] I have run `./build/test.py` and all tests pass

### CODE REVIEW

**Comment by avelad** [comment]
@nick-michael  One question, doesn't the same thing happen with ac-3?

**Comment by nick-michael** [comment]
> @nick-michael One question, doesn't the same thing happen with ac-3?

Probably, although I haven't got access to mixed (encrypted & unencrypted) content with AC3 audio tracks to test. I only noticed this while playing back on Xbox on a stream that has EC-3 and was able to verify that this fixed the problem. Happy to add a duplicate block for `avc3` as a preventative measure if you think it's a good idea.

**Comment by avelad** [comment]
@nick-michael , I've been looking, and the block should be `ac-3`.

I think it's a good idea to add it, but the expert is @joeyparrish

**Comment by nick-michael** [comment]
Ok no worries, I also reckon it makes sense to add it in but since I'm in no rush to get this merged on my side I'm happy to defer the decision

**Review by joeyparrish — APPROVED** [review]

**Pull request merged**
