### PR TITLE
Fix: Change in Resolution

### LINKED ISSUE #3262: Bug: Change in Resolution
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**What browser and OS are you using?**
Browser-Chrome, Firefox OS-Ubuntu 20.04

**What did you do?**
Create a simple HTML page with myapp.js
Change resolution from auto to 360p not (max. resolution possible change to any resolution but max.)
Change the language from the current language to any new language
See resolution changes to the max. 

**What did you expect to happen?**
Resolution should remain the same as it was before.

**What actually happened?**
Resolution changes after it is set manually (other than max.) to the max. resolution after language is changed.

image

image

### PR DESCRIPTION
**Pull request by aditmehta9**
## Description

Fix the bug where resolution changes when language is changed.
Fixes #3262 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

## Checklist:

- [x] I have signed the Google CLA <https://cla.developers.google.com>
- [x] My code follows the style guidelines of this project
- [x] I have verified my change on multiple browsers on different platforms
- [x] I have run `./build/all.py` and the build passes

### CODE REVIEW

**Comment by aditmehta9** [comment]
@TheModMaker please review.

**Comment by TheModMaker** [comment]
It is not the job of ABR to filter tracks, that should be handled by the player.  The Player currently filters the track list based on the currently-selected language.  I don't think we should change the ABR interface for this.  This also doesn't allow us to change how resolution selection works later (e.g. see #3141).

It would be better to have this handled in the language selection UI element.  It should look at the resolution selection and switch to using `player.selectVariantTrack` instead of `player.selectAudioLanguage`.

For any API changes, you should discuss this on the issue first to make sure we are ok with it.  It is better to avoid API changes unless we are adding new features that cannot be done with an existing API.  Anything in `externs/shaka` is part of our public plugin interface.

**Comment by aditmehta9** [comment]
> It is not the job of ABR to filter tracks, that should be handled by the player. The Player currently filters the track list based on the currently-selected language. I don't think we should change the ABR interface for this. This also doesn't allow us to change how resolution selection works later (e.g. see #3141).
> 
> It would be better to have this handled in the language selection UI element. It should look at the resolution selection and switch to using `player.selectVariantTrack` instead of `player.selectAudioLanguage`.
> 
> For any API changes, you should discuss this on the issue first to make sure we are ok with it. It is better to avoid API changes unless we are adding new features that cannot be done with an existing API. Anything in `externs/shaka` is part of our public plugin interface.

Thank you very much for the review. Next time I'll open an issue before making any changes in API. Sir, when I used selectVarianttrack it doesn't allow me to change the language once I have changed the resolution inside the resolution_selection.js file.

**Comment by TheModMaker** [comment]
Changing the language just involves selecting a track with the selected language.  With ABR disabled, it will just cause us to select a different track and update some internal fields.

I think the best fix would be to change `player.selectAudioLanguage` to accept a track object as the third argument.  This would override the default-selected track when switching to another language.  This would allow the UI to select the correct track based on the resolution and the Player will update its internal fields in `selectAudioLanguage`.  The track argument would be optional, if not given we'd select the default based on ABR.

**Comment by aditmehta9** [comment]
@TheModMaker so this PR is right?

**Pull request closed without merging**
