### PR TITLE
fix(tests): Load node modules more selectively.

### PR DESCRIPTION
**Pull request by theodab**
Change-Id: I73027d6f7dd11df2ec21d8dad7d601d3badda72e

## Description

Instead of loading all javascript files in all node modules, this only loads files from
the relevant modules. This ideally should fix the recurring problems with loading `less.js`,
but I have been unable to reproduce those problems locally or in my branch so I am not 100%
sure that will be the case.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [X] I have signed the Google CLA <https://cla.developers.google.com>
- [X] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have verified my change on multiple browsers on different platforms
- [X] I have run `./build/all.py` and the build passes
- [X] I have run `./build/test.py` and all tests pass

### CODE REVIEW

**Comment by theodab** [comment]
While testing this manually I discovered that, when running the screenshot tests locally, some of them fail for me.
```
Chrome 98.0.4758.80 (Mac OS 10.15.7) TextDisplayer layout using browser-native rendering two basic cues FAILED
	Error: native-two-basic-cues: Expected 0.8976168042876234 not to be less than 0.95.
	    at <Jasmine>
	    at Function._callee4$ (test/test/util/util.js:460:46 <- test/test/util/util.js:759:58)
	    at tryCatch (node_modules/babel-polyfill/dist/polyfill.js:6900:40)
	    at Generator.invoke [as _invoke] (node_modules/babel-polyfill/dist/polyfill.js:7138:22)
Chrome 98.0.4758.80 (Mac OS 10.15.7) TextDisplayer layout using browser-native rendering cues ending exactly now FAILED
	Error: native-end-time-edge-case: Expected 0.8904604092259658 not to be less than 0.95.
	    at <Jasmine>
	    at Function._callee4$ (test/test/util/util.js:460:46 <- test/test/util/util.js:759:58)
	    at tryCatch (node_modules/babel-polyfill/dist/polyfill.js:6900:40)
	    at Generator.invoke [as _invoke] (node_modules/babel-polyfill/dist/polyfill.js:7138:22)
```
After several hours trying to figure out which UI library I was forgetting to load, I discovered that those tests also fail for me without this change. Annoying! Well, it passes on a GitHub actions run in my fork, so it's probably fine.

**Review by joeyparrish — CHANGES_REQUESTED** [review]

**Comment by theodab** [comment]
Today, `karma-local-wd-launcher` is erroring while trying to update `msedgedriver`, and keeping me from doing any local tests. I wonder if some Microsoft server is down.

**Comment by joeyparrish** [comment]
> Today, `karma-local-wd-launcher` is erroring while trying to update `msedgedriver`, and keeping me from doing any local tests. I wonder if some Microsoft server is down.

I saw that on another PR.  I'll take a look.

**Comment by joeyparrish** [comment]
> > Today, `karma-local-wd-launcher` is erroring while trying to update `msedgedriver`, and keeping me from doing any local tests. I wonder if some Microsoft server is down.
> 
> I saw that on another PR. I'll take a look.

In the meantime, feel free to update the PR anyway.  If it passes on Windows and Linux VMs, that's good enough for me for the moment.  We can ignore Mac for now if we know there's an unrelated issue.

**Comment by joeyparrish** [comment]
> Today, `karma-local-wd-launcher` is erroring while trying to update `msedgedriver`, and keeping me from doing any local tests. I wonder if some Microsoft server is down.

I just triggered a workflow for `webdriver-installer` to see if this issue was reproducible, and it's working on Mac now: 
 https://github.com/joeyparrish/webdriver-installer/runs/5162259311?check_suite_focus=true

(The same run failed on Windows, but I expect that will be resolved in a moment.)

It looks like we just caught Microsoft at the wrong point in their deployment cycle for msedgedriver 98.  The failing run on [this PR](https://github.com/google/shaka-player/runs/5159718462?check_suite_focus=true) tried to install 98.0.1108.50, and now it's installing 98.0.1108.51 successfully.  It's all based on some text files Microsoft serves to tell you what version you should have, and now they've been properly updated.

**Comment by joeyparrish** [comment]
MS Edge 98 was _just_ released as the new stable version yesterday.  The matching driver release appears to still be catching up.  GitHub has already updated Edge to 98 on Mac & Windows (not installed by default on Linux VMs).

**Comment by joeyparrish** [comment]
Judging by the failure in Linux+Chrome tests, this isn't working as we expected.  :-(  It's still giving the same error about missing less.js.

(The other failures are due to the launcher, which will be updated in #3943.)

**Comment by theodab** [comment]
In that case, I'll close this PR.

**Pull request closed without merging**
