### PR TITLE
Fix the playback speed reset to 1 with pause/play #3261

### PR DESCRIPTION
**Pull request by sradhanjan**
fixes the playback speed issue

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by surajkumar-sk** [comment]
@sradhanjan this still doesn't fix the problem.

**Comment by sradhanjan** [comment]
@surajkumar-sk But in my case it's working alright

(before pressing pause/play button)
image
(after pressing pause/play button)
image

**Comment by surajkumar-sk** [comment]
@sradhanjan was removing one line from `player.js` was the only change you did?

**Comment by sradhanjan** [comment]
@surajkumar-sk Yes

**Comment by surajkumar-sk** [comment]
@sradhanjan I made the change but it doesn't work for me. I think some recent commits have something to do with it. Could you please update your repo on GitHub and locally on your computer and then make the change and try.

**Comment by sradhanjan** [comment]
@surajkumar-sk Should I clone the shaka-player repo and try the changes again??

**Comment by surajkumar-sk** [comment]
yes

**Comment by sradhanjan** [comment]
@surajkumar-sk As requested, I have cloned the updated shaka-player repo. Made the same change again and ran the project locally but still it is solving the playback speed issue.

**Comment by nbcl** [comment]
Hello @sradhanjan!

This solves the problem for me!

Now, maybe you could also try considering the other instance in line 3171:

https://github.com/google/shaka-player/blob/c5af2be27a2256e699763e0570235b30838ed2aa/lib/player.js#L3171

Which may also be causing the described behavior in some cases, and could be the reason why the fix is not working for @surajkumar-sk.

On the other hand, regarding [this comment](https://github.com/google/shaka-player/issues/3261#issuecomment-804206315) back in #3261:

> In the UI control for playback rate, we could set both playbackRate and defaultPlaybackRate. In cancelTrickPlay() or anywhere else we set playbackRate to 1, it would instead be set to defaultPlaybackRate. 

It appears to be that, instead of removing lines 3171 and 3175, maybe you could try to make them set  a `defaultPlaybackRate`, which would be initially assigned back in the UI control for it, at `ui/playback_rate_selection.js`. 

The objective of that approach is fixing the issue while also maintaining [this functionality](https://github.com/google/shaka-player/issues/3261#issuecomment-804194623)!

Please, let me know what you think about this, and I will be happy to help if you have any questions regarding the new approach!

**Comment by sradhanjan** [comment]
@nbcl Ok, I will try to fix this issue using other approaches too
@surajkumar-sk can I know which line have you deleted ? line no. 3171 or 3175

**Comment by surajkumar-sk** [comment]
3175

**Comment by sradhanjan** [comment]
@surajkumar-sk I think now it would be better if any member gives it's conclusion on this fix. If they are not satisfied with this solution I will try my best to come up with a new one.

**Comment by sradhanjan** [comment]
@googlebot I signed it!

**Comment by joeyparrish** [comment]
I don't believe it's right to delete that line, because it will break our trick play feature.  See my description of trick play here: https://github.com/google/shaka-player/issues/3261#issuecomment-804194623

Instead, I think we should use what I suggested here: https://github.com/google/shaka-player/issues/3261#issuecomment-804206315

**Comment by sradhanjan** [comment]
Ok, I will try to fix this issue using https://github.com/google/shaka-player/issues/3261#issuecomment-804206315 approach.

**Pull request closed without merging**
