### PR TITLE
VTT on digit hour fix.

### PR DESCRIPTION
**Pull request by esteban-dosztal**
This fixes an issue that happens because ffmpeg, when converting from .srt to .vtt, strips the zero in '0n', where 0 < n < 10, from the times with hour < 10.

Thanks.

### CODE REVIEW

**Comment by joeyparrish** [comment]
@esteban-dosztal, please add a test case in test/media/vtt_text_parser_unit.js.  You can run tests with ./build/test.py.  Also, please read CONTRIBUTING.md and add yourself to AUTHORS and CONTRIBUTORS.  Thanks for the contribution!

**Comment by esteban-dosztal** [comment]
Thanks! I'm closing this PR and continue this thing in this one https://github.com/google/shaka-player/pull/522. Made the mistake of creating a PR from master branch, sorry, my fault.

**Comment by joeyparrish** [comment]
No, master branch was correct.

**Comment by joeyparrish** [comment]
Oh, I see, you meant your master branch.  That part really doesn't matter to us.  As long as you're merging into our master.  We fork at each .0 release and merge cherry-pick bugfixes into the fork.

**Pull request closed without merging**
