### PR TITLE
Added missing @exportDoc annotations

### PR DESCRIPTION
**Pull request by mrlika**
Those externs are referenced in other parts of documentation

### CODE REVIEW

**Comment by mrlika** [comment]
Also typo should be fixed shakaExtern.TimelineregionInfo => shakaExtern.TimelineRegionInfo:

```
/**
 * @event shaka.Player.TimelineRegionExit
 * @description Fired when the playhead exits a timeline region.
 * @property {string} type
 *   'timelineregionexit'
 * @property {shakaExtern.TimelineregionInfo} detail
 *   An object which contains a description of the region.
 * @exportDoc
 */
```

**Comment by TheModMaker** [comment]
Thanks for finding this.  Do you want to fix the typo also?

**Comment by mrlika** [comment]
Yes, I can. Should the typo be fixed in this pull request or in a new one?

**Comment by TheModMaker** [comment]
You can just update this one.

**Comment by joeyparrish** [comment]
Cherry-picked to v2.3.1.

**Comment by joeyparrish** [comment]
Cherry-picked for v2.2.10.

**Pull request merged**
